// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXOawp-weQ1i99oyYOLbLvT3WqDQ8U_c',
    appId: '1:185292801179:web:d10b129cd2748d1902323e',
    messagingSenderId: '185292801179',
    projectId: 'cins467-f23',
    authDomain: 'cins467-f23.firebaseapp.com',
    storageBucket: 'cins467-f23.appspot.com',
    measurementId: 'G-JZ164Q46SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03IKwREIhiCdVH7bdTOnC3sxbnigTegI',
    appId: '1:185292801179:android:e49644a67aaa568a02323e',
    messagingSenderId: '185292801179',
    projectId: 'cins467-f23',
    storageBucket: 'cins467-f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27WUbYyRU5EzujpsY4oNkskKW_x7DzS8',
    appId: '1:185292801179:ios:ab3e8818956af6d202323e',
    messagingSenderId: '185292801179',
    projectId: 'cins467-f23',
    storageBucket: 'cins467-f23.appspot.com',
    iosBundleId: 'com.example.buybox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27WUbYyRU5EzujpsY4oNkskKW_x7DzS8',
    appId: '1:185292801179:ios:b905ba5f48daeb5d02323e',
    messagingSenderId: '185292801179',
    projectId: 'cins467-f23',
    storageBucket: 'cins467-f23.appspot.com',
    iosBundleId: 'com.example.buybox.RunnerTests',
  );
}
